# Generated by Django 3.2 on 2025-06-18 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название пункта меню')),
                ('menu_name', models.CharField(max_length=100, verbose_name='Название меню')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL (явный)')),
                ('named_url', models.CharField(blank=True, max_length=100, verbose_name='Named URL')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
