# Generated by Django 3.2 on 2025-06-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_menuitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(help_text='Уникальный идентификатор пункта меню', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
